### ISSUE TITLE
Ignore sheet, libparts and libraries sections in kicad netlists

### ISSUE THREAD

**Issue by kasbah** [electron-lang/libkicad#1]
version: 0.1.0-next.711c68e

https://cloud.monostable.co.uk/component_tester.net

```js
const {netlist} = require('libkicad')
const fs = require('fs')

const n = netlist.parse(fs.readFileSync('./component_tester.net').toString())

console.log(n)
```

```
/home/kaspar/projects/kitspace/kitspace/node_modules/libkicad/lib/netlist/parser.js:441
        throw new Error("msg: " + error.message + " ln: " + error.token.startLine + " " +
        ^

Error: msg: Expecting --> ) <-- but found --> '(' <-- ln: 6 col: 5
    at Object.parse (/home/kaspar/projects/kitspace/kitspace/node_modules/libkicad/lib/netlist/parser.js:441:15)
    at Object.<anonymous> (/home/kaspar/projects/kitspace/kitspace/packages/part-extract/index.js:4:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by dvc94ch** [comment]
Did you generate it with kicad? You need to remove some parts that aren't parsed. The (sheet), (libparts) and (libraries) tags
